remote_theme: "mmistakes/minimal-mistakes@4.21.0"
plugins:
  - jekyll-remote-theme
  - jekyll-feed

title: "Steven Bontius"
subtitle: "Deep Learning Portfolio"
description: "HAN University - Deep Learning Course"
author:
  name: "Steven Bontius"
  bio: "Data science student at HAN University"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/StevenBontius/"

minimal_mistakes_skin: "dark" 